### ISSUE TITLE
alpha-state-problems

### ISSUE THREAD

**Issue by Neohiro79** [PeterWone/vsc-print#1]
I got the special VSC-load of that folder.

First message inside:
The terminalprocess has beeing terminated with exitcode 1

**Comment by PeterWone** [comment]
I'll check in a build that can run, so you can validate your setup.

**Comment by Neohiro79** [comment]
that's great, thanx

**Comment by Neohiro79** [comment]
also it would be nice if you could provide me with some basics, I might post some questions later in here, since I am not that deep into building extensions with VSC/node etc. pp.

**Comment by PeterWone** [comment]
I checked it out on another machine and had some problems. Check whether something hasn't hijacked your node installation. On one of my systems SAP SqlAnywhere had quietly changed my system path to point at their own prehistoric version of node. The most reliable fix is to install the current production build from nodejs.org which also guarantees you have a suitable version. In addition I think my package.json wasn't quite right. I'll check in and check out to test and I'll let you know when it's good to go.

**Comment by PeterWone** [comment]
The error you are seeing is environmental. Make sure node is current, and after you clone, don't forget `npm i` to fetch the modules specified in package.json

**Comment by PeterWone** [comment]
Also if the vscode library acts like it's missing even though you can see it's present, `npm i` fixes it.

**Comment by PeterWone** [comment]
The latest push fixes a lot of issues. I've figured out how to get the CSS from the highlight.js styles at run-time. I'm building an all-in-one html file than gets written to the disk, you'll need console to find it but you can inspect it with a browser and it works perfectly. Also you may notice the Print button at the top right of the titlebar. I am also detecting the file to print based on the parameter passed when my handler is invoked so it prints the right file when you right click in the file explorer.

Remaining items are conversion to a webserver so I don't leave temp files everywhere, and launching the browser. Both of these can be lifted from printcode, and after that it's all about the settings. If all goes well you'll be able to pick a stylesheet from a list populated from the styles folder of highlightjs (about 30 schemes) and eventually I'll provide UI for adding your own CSS files.

**Comment by Neohiro79** [comment]
Alright, sounds superiour at all - I will try to dive a bit into it the next days, I will give you feedback as soon as I can, hope I will have some time the next days to go through it! :-)

**Comment by Neohiro79** [comment]
I've installed node.js - but VSC still won't find node.js.

I've looked into the environment-variables of windows and there is still no node.js, eventhough the installer run through.

Do I have to manually set any path in there to get it to work (when pressing F5) or do I need to install a "debugger" via VSC itself?

**Comment by PeterWone** [comment]
I couldn't say but you can try release 0.2.0 which is now a published extension.

**Comment by Neohiro79** [comment]
I've copied it into VSC extension folder - but I cannot activate it - all other extensions do give that option.

**Comment by Neohiro79** [comment]
**PERFECT** !!!

**Comment by Neohiro79** [comment]
Now I guess I need to get the icons to work - at least if I can get the dev-environment to work correctly.

**Comment by PeterWone** [comment]
I'm going to close this because it's not actually an issue.
