### ISSUE TITLE
Alternate Browser Path setting doesn't work in Linux

### ISSUE THREAD

**Issue by baincd** [PeterWone/vsc-print#100]
The browser does not launch when the property `print.browserPath` is set on a Linux workstation.  

I believe the root cause is [this line](https://github.com/PeterWone/vsc-print/blob/91b1a5c80f00cebbc542175a46dd4c78124af6e9/src/extension.ts#L135):
```typescript
  let cmd = printConfig.alternateBrowser && printConfig.browserPath ? `"${printConfig.browserPath}"` : browserLaunchMap[process.platform];
```
which always wraps `printConfig.browserPath` in double-quotes. If the double-quote wrapping were removed, the command would work in Linux

I think a better approach would be to not automatically wrap the command in double-quotes.  If a command requires double-quotes (such as a Windows path that has spaces), the double-quotes could be included as part of the property value.  This would also allow for the flexibility of the user passing in command-line options if they want.  For example, the following values for `print.browserPath` would then be supported:

- `/usr/bin/google-chrome-stable` (Linux)
- `/usr/bin/google-chrome-stable --incognito` (Linux with a command line option)
- `"C:\Program Files\Chrome\chrome.exe"` (Windows with path that has a space)
- `"C:\Program Files\Chrome\chrome.exe" --incognito` (Windows with a command line option)

Of course, this change would need to be considered carefully since would break existing configurations that configur the `print.browserPath` property

**Comment by PeterWone** [comment]
For windows only, on startup and on change of the alt path, test the value for spaces and add quotes where necessary. 

Adding quotes is going to be complicated in the presence of command line options.

**Comment by PeterWone** [comment]
@baincd does this work now?

**Comment by baincd** [comment]
@PeterWone I tested this on Linux and it works!  Thank you!!
