### ISSUE TITLE
Syntax-coloured ?

### ISSUE THREAD

**Issue by joe-oli** [PeterWone/vsc-print#102]
All I get is grayscale, how to get colour?

**Comment by PeterWone** [comment]
You need to change your printing theme. [Details of how are in the manual](https://github.com/PeterWone/vsc-print/blob/master/manual.md#choose-a-colour-scheme).

**Comment by joe-oli** [comment]
Thank you Peter, I will work through the manual - It's a bit advanced for me, I've been a developer for 20+ years, but CSS just goes over my head.

**Comment by PeterWone** [comment]
The engine I used for the syntax colouring comes with a bunch of pre-fab stylesheets. I ship the lot. Many are dark theme, hence the warning.
