### ISSUE TITLE
Support local markdown stylesheets

### ISSUE THREAD

**Issue by caseychu** [PeterWone/vsc-print#106]
Hello, thanks for the very useful extension!

I have a local stylesheet configured for my workspace:
```
"markdown.styles": [
  "md-style.css"
],
```
However it doesn't take effect on the printed page. (It seems like the issue is simply that the path is directly passed to the HTML without transformation whereas it should be transformed to load it from the server.)

**Comment by PeterWone** [comment]
You are correct and this is a consequence of the completely different pipeline used for Markdown. I actually realised there would be a problem with this about two weeks ago but have not had time to address it.  

If you put the stylesheet in the same folder as the markdown file it may work. 

I will give this some attention over the next week.

**Comment by PeterWone** [comment]
Or maybe [Microsoft broke it](https://github.com/Microsoft/vscode/issues/33455)

**Comment by caseychu** [comment]
Thanks for taking a look so quickly. Yes, my custom styles in that file do take effect in the Markdown preview pane.

**Comment by PeterWone** [comment]
And are they in the same folder as the document?

**Comment by caseychu** [comment]
Yes, my stylesheet and Markdown files are all in the same folder (the workspace root). Actually, the preview pane seems to search for the stylesheet relative to the workspace root -- if I make a Markdown file in a subdirectory, the preview pane still reads the stylesheet fine.

**Comment by PeterWone** [comment]
This is resolved in the next release. Stylesheets are now bundled.

![image](https://user-images.githubusercontent.com/5498936/131256833-73640d6a-5e73-43b7-8a5c-8738ab6f5fce.png)
