### ISSUE TITLE
Cannot print to browser because of missing file or directory.

### ISSUE THREAD

**Issue by RetroAnkit** [PeterWone/vsc-print#116]
I'm using Linux and after clicking on print, I got this error in browser:

```
Error: ENOENT: no such file or directory, open '/home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/node_modules/highlight.js/styles/default.css'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
	at T (/home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:908842)
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:906535
	at Generator.next (<anonymous>)
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900819
	at new Promise (<anonymous>)
	at a (/home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900564)
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:905132
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:908481
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:904309
	at Generator.next (<anonymous>)
	at /home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900819
	at new Promise (<anonymous>)
	at a (/home/pc/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:900564)
	at Server.<anonymous> (/home/ankit/.vscode-oss/extensions/pdconsec.vscode-print-0.9.8/dist/extension.js:2:904074)
	at Server.emit (events.js:315:20)
	at parserOnIncoming (_http_server.js:874:12)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
```

**Comment by PeterWone** [comment]
The error clearly states what is missing and where it should be. This raises two questions:

* Why isn't it there?
* What can you do about it?

# Why isn't it there?

* The installation was botched. The missing files _are_ in the VSIX file, I checked. 
* You're not using VS Code, you're using a non-standard fork of it which I can tell by the name of the folder `/home/pc/.vscode-oss`
* The installation was botched. The missing files _are_ in the VSIX file, I checked. 
* You're using an obsolete version of the extension (current is 0.9.13) which tells me that updates are not being applied. So either you've been interfering with settings or the installer in your non-standard version of VS Code has non-standard behaviour.
* The installation was botched. The missing files _are_ in the VSIX file, I checked. 

How on Earth can anyone mess up a one click install? This is an interesting question (you aren't the first). Possibly by using a non-standard version of VS Code?

# What can you do about it?

* Check whether that path exists, starting with '/home/pc/.vscode-oss`
* If the path is valid then add the files. 

VSIX files are just zip files. If you rename one and look inside you will find this

![image](https://user-images.githubusercontent.com/5498936/134749537-24b137cc-ffa1-449e-a38c-3d36950af400.png)

which contains this

![image](https://user-images.githubusercontent.com/5498936/134749650-d9ae997a-8b61-4779-95fd-d3f93e42685a.png)

**Comment by RetroAnkit** [comment]
Thanks for your assistance. I pasted the `.css` files and it works fine now.

**Comment by matkoniecz** [comment]
> How on Earth can anyone mess up a one click install? This is an interesting question (you aren't the first). Possibly by using a non-standard version of VS Code?

yep, I use VSCodium that apparently is causing some issues

> Perhaps you could raise an installer issue on the code-oss repository

Done! https://github.com/VSCodium/vscodium/issues/928

> In the short term, how can you patch your own setup?

In my case entire `node_modules` was missing.

It is also missing from VSIX file at https://open-vsx.org/extension/pdconsec/vscode-print

It is not missing from VSIX file at https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print
