### ISSUE TITLE
LaTeX print missing equation numbers

### ISSUE THREAD

**Issue by dsernst** [PeterWone/vsc-print#118]
Hi— I learned about this extension from VSCode's docs page recommending it as a way to extend the built-in markdown support: https://code.visualstudio.com/Docs/languages/markdown

I'm writing a markdown file w/ embedded LaTeX equations:

```md
<!-- prettier-ignore-start -->

# Example title

## This is a great markdown subheading

Now let's do some *LaTeX* with equations:

$$\begin{equation}
\hat x_i = x_i * b
\end{equation}$$

$$\begin{equation}
\hat y_i = y_i * \gamma * b
\end{equation}$$

Back to normal body text.

<!-- prettier-ignore-end -->
```

This is from the official KaTeX docs: https://katex.org/docs/supported.html#environments

Here's how it looks in the built-in VSCode markdown preview:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/6340841/142615566-2f733f46-f5ce-4b60-b5e4-859aafb711be.png">

But when I use this extension to Print > Open in Browser (Safari), this is what I get:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6340841/142616777-b9baf252-ffd6-4700-b3d6-5247e0758eea.png">

Which is so close to right! But missing those right-aligned numbered equation labels.
AFAICT, they're not in the rendered HTML at all.

Do you have any insight into this?

-----

I don't think this is relevant, but this screenshot is also after I added this custom css rule because the LaTeX was double rendering:
```css
.katex-html {
  display: none;
}
```
)

**Comment by PeterWone** [comment]
Thank you for providing a repro sample. 

The way the print extension works is it hijacks the rendering pipeline that VS Code uses for the preview - it's the _same_ pipeline. This kind of problem shouldn't be possible. But obviously it is. What I may have to do is spin it up in a debugger and see what's produced when your document is processed.

**Comment by dsernst** [comment]
Sure thing, thank you for this awesome open-source lib! 🙏

I wanted to get this report in, and then I noticed the instructions about adding the KaTeX stylesheet: https://github.com/PeterWone/vsc-print/blob/master/manual.md

That fixed the double rendering issue fyi 🙂.

But not this missing equation labels one.

**Comment by PeterWone** [comment]
OK this is what it sends to the preview pane WebView 

![image](https://user-images.githubusercontent.com/5498936/142621406-dcdd02a2-c6f9-45f9-a383-30a5b07b8e87.png)

**Comment by dsernst** [comment]
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/6340841/142623030-e9e58be7-3b5b-415b-bd39-86273250d9b9.png">

I chased it down in Safari debugger... looks like I'm missing that `::before` pseudo class. Hmmm 🤔

**Comment by dsernst** [comment]
Not just happening in Safari, also reproducing in Chrome 95 and Firefox 92 (all on Mac).

**Comment by PeterWone** [comment]
And in Edge on Windows. It's real, and it isn't the browser. However I have other things I need to finish tonight and it's almost eleven. 

I spun it up in my debugger and triggered the problem. This is the code that calls into the rendering pipeline to convert the Markdown to HTML.

![image](https://user-images.githubusercontent.com/5498936/142630209-5d06c22e-1f69-4138-8730-850e0197e579.png)

And the `::before` is missing from the conversion.

![image](https://user-images.githubusercontent.com/5498936/142630396-a3048601-30ad-4cc8-a4f9-b2e988fa4be4.png)

Why is it missing? Hell if I know. I'll have to consult the fellow who maintains the Math+Markdown extension. Could be a while before I sort _this_. Well done, it appears you're _that_ guy. Boards derelict space station, says look at all this cool stuff! Opens hatch, says "What's that flashing red light labelled _main reactor_?" Which is a huge improvement on "Why is it getting warmer?"

**Comment by dsernst** [comment]
Yes, confirmed that updating the CSS file fixes this! 🎉

Thanks for such speedy help ❤️

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/6340841/142680269-8fb84b4a-4aca-45a0-af1c-cab47ef05cb2.png">

**Comment by PeterWone** [comment]
As a matter of interest, in the course of figuring this out I discovered that the MathPix extension also works with printing. It's a wrapper for KaTeX but it also supports SMILES notation allowing you to produce diagrams like this.

![image](https://user-images.githubusercontent.com/5498936/142701070-da37c9d4-aa07-47a3-8f2c-9b6e98f18571.png)

**Comment by dsernst** [comment]
Super cool.

I also loved your "derelict space station" metaphor! 🪃
