### ISSUE TITLE
Printed-Page Headers and Footers: How Do I Show the File Path in the Header?

### ISSUE THREAD

**Issue by Imaginativeone** [PeterWone/vsc-print#128]
I've been printing source-code within Visual Studio Code by using this extension for years. The full file path was printed, as a header, on each of my pages. On the bottom(s), the page number "Nthis/Ntotal" was printed as a footer. I did something to make it so that only my code prints, without the headers/footers.

Would you help me to put the headers/footers back? Thanks in advance.

**Comment by Imaginativeone** [comment]
This issue appears to have worked itself out.

**Comment by PeterWone** [comment]
I apologise for the lengthy silence. My day job was taking all my time. I'm glad you were able to resolve the issue.
