### ISSUE TITLE
Select Tab Size

### ISSUE THREAD

**Issue by rorlork** [PeterWone/vsc-print#15]
It would be great to be able to select the tab size. Right now it depends on the browser, in mine it appears to use a tab-size of 8. This can be changed through a style, and it would be very welcome to have.

I suppose this could be accomplished by modifying the style, but I think it would be much nicer to have as an option.

**Comment by PeterWone** [comment]
There are a couple of settings I use for markdown rendering where I embed the value into CSS. I think the thing to do is use the existing tab size setting in this way. What do you think?

**Comment by rorlork** [comment]
The existing tab size setting from VSC? that would be even better than what I thought so yes, that would be perfect

**Comment by PeterWone** [comment]
I have implemented this in 0.5.3 using the tab-size CSS experimental property. The specification says it is inherited so setting it on the body tag should work.

This is an experimental property. It is not supported by Edge and it is subject to change. That said, when Edge switches to the Chromium engine all major browsers will be supported, and having read the spec I don't think it's likely to change.

To make this work in older browsers I would need to replace every \t with some number of spaces (the stylesheet is space preserving). This is actually not hard so I may yet do so.

**Comment by PeterWone** [comment]
Changed my mind, I'm not supporting IE, it's deprecated.
