### ISSUE TITLE
Add menu entry in File

### ISSUE THREAD

**Issue by rorlork** [PeterWone/vsc-print#16]
The most frequent place one finds the Print command in other programs is in the File menu in the menu bar. It would be nice to have it there, maybe even more than having it in the right-click menu, which I would expect to be reserved to actions that one performs more frequently than printing.

To print the selected text, the same could be done under the Selection menu in the menu bar.

**Comment by PeterWone** [comment]
Thanks for the feedback. 

I actually intended to put Print in the File menu but couldn't figure out how. I don't think it's supported by contributions in the package.json file but if you can tell me how to do I I'm interested.

**Comment by rorlork** [comment]
I have no idea, honestly. I thought that it might be possible but I've never made an extension for VSC. Looking through the documentation, the only thing that maybe might do it is the `editor/title` contribution point, but I'm unsure of what it really means. https://code.visualstudio.com/api/references/contribution-points#contributes.menus

Anyway, selection detection might be nice, although I'd at least move the menu option to the bottom of the context menu if it's to stay there, maybe.

**Comment by PeterWone** [comment]
Controlling the position in the menu is supported by the contribution mechanism. You think it should be at the bottom, I think it's convenient at the top... sounds like another config setting to me.

**Comment by PeterWone** [comment]
This may be harder than it looks. It's easy to change the position of the menu by editing the contribution in package.json but I don't (yet) know how to change it at run-time.

**Comment by rorlork** [comment]
Well, as you said, this was something that it's mostly a matter of preference so I'd say that it's not really important if it can't be made to work. Thanks for trying anyway!

**Comment by PeterWone** [comment]
Got it with some help in the gitter channel. You can't change the position of a contributed menu item but you can contribute two menu items for the same command with different when clauses, and there is an undocumented API command that allows you to define a symbol the when clause can see. So you got your wish!

**Comment by PeterWone** [comment]
You'll see it in 0.6.5
