### ISSUE TITLE
Settings > Set Port

### ISSUE THREAD

**Issue by chris-guidry** [PeterWone/vsc-print#25]
The extension used port 8000, but I needed that one for one of my apps. It would be nice to be able to set the port to avoid this conflict.

**Comment by PeterWone** [comment]
Port selection is dynamic. If you start your app first Printing should choose another port.

I could create a setting for exclusion. I'll look into whether the port selection library I'm using suipports this.

**Comment by chris-guidry** [comment]
An exclusion list would work. Thank you for considering it!

**Comment by PeterWone** [comment]
The utility in question is [PortFinder](https://github.com/indexzero/node-portfinder). It doesn't support exclusion ranges but it _does_ support a start and end for the free-port scan range.

I have to go to work ten minutes ago. If you submit a PR you'll get it quicker.

**Comment by PeterWone** [comment]
It's done and tested. You'll see it in the next release.

**Comment by chris-guidry** [comment]
Great, thank you @PeterWone!

**Comment by PeterWone** [comment]
@chris-guidry it's published to the marketplace. Would you be so kind as to confirm that it resolves your issue?

**Comment by chris-guidry** [comment]
@PeterWone just tested and it works well. I appreciate that the default min/max for the port covers an unusual range so it's unlikely to interfere for most people. Thanks again!

**Comment by PeterWone** [comment]
@chris-guidry if you think this extension is high quality and well supported you could write a review.
