### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jwinkt** [PeterWone/vsc-print#26]
Under what license is vsc-print provided?  Would you please direct me to the license?

Please add a license, such as
https://github.com/wayou/vscode-todo-highlight/blob/master/LICENSE.txt,

and add it to the vsc-print marketplace listing 
https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print

Thanks and regards,
John

**Comment by jwinkt** [comment]
Maybe just modify this one?
https://github.com/wayou/vscode-todo-highlight/blob/master/LICENSE.txt

**Comment by PeterWone** [comment]
The marketplace only supports free VS Code extensions and it’s not library code that might be incorporated into something larger. There’s no in-app attempt to upsell to a paid version.

Terms are the usual – make only truthful claims about provenance and authorship. There is a conceptual debt to nobuhito’s extension but I didn’t use any of his code so strictly speaking it’s not a derivative work and I don’t know how or even whether to acknowledge. Plus it goes much further, which was the point of the exercise.

Maybe I should say just that: “There is a conceptual debt to nobuhito’s extension but no code from that project was used.”

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PeterWone** [comment]
I added a modified MIT licence (no selling, acknowledge when deriving)
