### ISSUE TITLE
Cyrillic symbols problem and indent

### ISSUE THREAD

**Issue by vikegart** [PeterWone/vsc-print#29]
Hi
Cyrillic symbols are not supported right now.
![image](https://user-images.githubusercontent.com/18119270/58621413-632ebe80-82da-11e9-9ebf-073a67f64cd9.png)
How it looks from VS Code
![image](https://user-images.githubusercontent.com/18119270/58621461-80fc2380-82da-11e9-8164-79db2a80eea7.png)
I'll very appreciate if you can fix this issue

And so, you can see, that indent is not correct on a printed page.
![image](https://user-images.githubusercontent.com/18119270/58621638-eea84f80-82da-11e9-889d-26cc2239caab.png) Correct indent
![image](https://user-images.githubusercontent.com/18119270/58621732-1992a380-82db-11e9-88d2-28b2db05ba12.png) Incorrect indent

**Comment by PeterWone** [comment]
This is actually quite hard for me to debug but if you can guide me on what is needed for this to work correctly I would be happy to incorporate the changes. You are also welcome to fix it yourself and submit a pull request. Are you familiar with Typescript?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PeterWone** [comment]
Windows 10 won't let me install Cyrillic fonts unless I have a suitable language pack. You may _have_ to fix this yourself.

One of the settings is `Print: Print And Close`. By default this is switched on. If you turn it off you will be able to use F12 to examine the web page that is generated and sent to the browser for printing.

In the head of the web page you will find `<meta charset="utf-8">` and if you change this to `<meta charset="utf-16">` this may fix the font problem. I am not sure why the indenting is wrong but if you can manually fix the web page and then tell me what change you make then I may be able to correct it in the template.

**Comment by PeterWone** [comment]
No, I was wrong. But it just occurred to me that I have a Russian friend who may be able to help me experiment. Could you send me a copy of the file you used to demonstrate the problem?

**Comment by PeterWone** [comment]
I've just figured out the anomaly with the indenting. If you look closely at the screen capture you supplied, the line that appears to be incorrectly indented _does not have a line number_. This is a line that was too long and wrapped from the previous line. To stop this from happening you can either shorten the line or print in landscape mode. 

This leaves me with the question of why the text is not rendering with Cyrillic characters. I need two things from you:

* A sample file that produces the problem on your computer.
* The typeface you have set for `Editor: Font Family`

**Comment by PeterWone** [comment]
Don't worry about it, I have succeeded in reproducing the problem.

**Comment by PeterWone** [comment]
And now it's fixed. As of release 0.7.0 extended character sets are supported for code as well as for markdown.

**Comment by vikegart** [comment]
Hey! Sorry, that I took so long to answer. We're in different time zones, so I slept :)
Big thanks to you for that fix! You are an awesome developer!

**Comment by PeterWone** [comment]
0.7.0 is released now. Could you verify that the problem is fixed?

**Comment by vikegart** [comment]
Hi. I'm currently busy at work. But I've tested a new version and all works fine. Thanks.
So, I can help you with translating this to Russian. Can we discuss that in private messages?

**Comment by PeterWone** [comment]
Certainly. If you look in `package.json` for this extension you will find that you already have my email address.
