### ISSUE TITLE
Add ability to print unsaved text

### ISSUE THREAD

**Issue by CheckeredFlag** [PeterWone/vsc-print#31]
It appears that saving a file is required before the print icon becomes available.  However, there are times when I simply need to print a temporary snippet of text (e.g. sql query results, error message) and I don't need nor want to save the file.  If a file on disk is absolutely necessary, perhaps it can save it to a temp file that it can delete later.

**Comment by PeterWone** [comment]
I have reproduced this behaviour.

I don't use a file directly unless you print a document other than the active document using the file explorer. The problem you are seeing is a consequence of the way VS Code manages menus and toolbars -- it needs to know the file type, and this is inferred from the file extension, which depends on the file existing. 

Think through the behaviour you expect in the absence of a file type, and we can discuss supporting your use case.

**Comment by CheckeredFlag** [comment]
It should print without syntax coloring by default (i.e. Plain Text).  If I want language support such as syntax coloring, then I just click "Plain Text" in the lower right corner next to the smiley face and select the desired language.

I think by default unsaved buffers ought to print without line numbers.  Perhaps a context menu option or a default setting would be good.

**Comment by PeterWone** [comment]
I'm currently in the middle of internationalising the extension so it may be a while before I have time to deal with this. I have a feeling it's one of those small things with far-reaching effects -- I will no longer be able to let VS Code manage the UI automatically.

**Comment by PeterWone** [comment]
I think I may have a solution. Would you mind testing 0.7.5 and if it solves your problem let me know by closing this issue.

**Comment by CheckeredFlag** [comment]
Perfect - thanks!
