### ISSUE TITLE
Format XQL not printable

### ISSUE THREAD

**Issue by ThomasPerraudin** [PeterWone/vsc-print#32]
I can't print a .xql format.
Althought it may be an 'exotic' file format, I need to print it, at least in black & white.

**Comment by PeterWone** [comment]
Sample?

**Comment by ThomasPerraudin** [comment]
sample ?
- create a tests.xql file with random content
- open with VS Code
- the print icon is missing

**Comment by PeterWone** [comment]
Okay I can reproduce that. This is fundamentally the same problem as #31 and the workaround is the same:  paste content of interest into an open file of recognised type - a text file. Or you could rename the file then rename it back after printing. I'm still trying to figure out how to deal with this one as the problem is actually in the way VS Code manages toolbars and menus.

**Comment by ThomasPerraudin** [comment]
Sad :(
Actually this workaround is not acceptable for me. I am printing files as evidences and I must keep real names in printed headers.

**Comment by PeterWone** [comment]
As I said, it's under active consideration. I will give it serious thought this weekend. Can you wait that long?

Incidentally, if you can spare the time would you mind having a look at readme.fra.md and manual.fra.md? French is a second language for me so the quality of translation will be poor.

**Comment by PeterWone** [comment]
I think I can help you out, although it's not a solution fit for production.

In the package.json file around line 140 you will find this

```
		"menus": {
			"explorer/context": [
				{
					"when": "resourceLangId",
					"command": "extension.print",
					"group": "navigation"
				}
			],
```
If you remove the `when` property then the print icon will always appear. Beware that if you click it and there is no active editor it will probably crash.

**Comment by ThomasPerraudin** [comment]
Arg it doesn't work. Your French files are not perfect but it's ok.

**Comment by PeterWone** [comment]
I believe I have found a fix here <https://github.com/PowerShell/vscode-powershell/pull/1475>

It looks like the same problem and I have just tested it on an xql file with success. It also appears to address #31 so I will roll out an update ASAP.

**Comment by PeterWone** [comment]
It's done. 0.7.6 will be out shortly with the updated readme and changelog but you don't need that to proceed.

**Comment by ThomasPerraudin** [comment]
It works ! Thank you very much !

**Comment by PeterWone** [comment]
I'm looking for a French native speaker to handle translation. Perhaps you know someone who would like to be involved. I can read French but I'm horrible at writing it.

**Comment by ThomasPerraudin** [comment]
I am personaly too busy for that but I know a professional translator if you want.

**Comment by PeterWone** [comment]
It’s unpaid open source, so there is no budget, it cannot be a commercial arrangement.

It’s really just a courtesy – people in France were so nice to me when I travelled there, patiently waiting while I mangled your language.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
