### ISSUE TITLE
Stylesheet cache path is wrong on Mac

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#35]
On OS/X, `Print: Browse stylesheet` fails with an error because the path is wrong. Providing a path directly works but this does not import the stylesheet to the cache and is brittle.
![image](https://user-images.githubusercontent.com/5498936/60055243-560dbf80-9720-11e9-9a64-668381a157ae.png)

**Comment by PeterWone** [comment]
I think I have this figured out. I'll release a proposed fix 0.7.8 and if you would be so kind as to test it for me perhaps we can close the issue.

**Comment by PeterWone** [comment]
@18KaiZer71 would you mind testing this on your Mac?

**Comment by 18KaiZer71** [comment]
Doesn‘t seem to work for me. I don‘t get an error message anymore and the theme changes in the settings, but the UI is stays the same.

**Comment by PeterWone** [comment]
The UI stays the same? VS Code has its own theme.

[cid:image001.png@01D52F7B.0CE9CEF0]

I made the print theme independent because some people use a dark theme on the screen but printer paper is generally white (or light coloured).

The UI isn’t supposed to change, but the printing theme colours should take effect. I will test this and verify that it is the case. If it isn’t so then I’ll raise a new issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PeterWone** [comment]
The UI isn't _supposed_ to change. VS Code already has UI theme management.

![image](https://user-images.githubusercontent.com/5498936/60394925-017aa200-9b6f-11e9-9783-6e279d17a5c5.png)

Many people use dark themes on screen, and these are unsuitable for printing because paper is generally white. For this reason I made the print theme completely separate.
