### ISSUE TITLE
Add link to VS Code Marketplace or add name here

### ISSUE THREAD

**Issue by byronwall** [PeterWone/vsc-print#36]
Spent more time than I expected searching for the extension in VS Code.  Between the logo and company name, it wasn't obvious which extension was correct.  A link to the Marketplace or the name of the extension here may be helpful for future users who land on the Github page instead of the Marketplace page.

Marketplace link: https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print

Great extension once installed.

**Comment by PeterWone** [comment]
You couldn't _guess_ that PDCONSEC is Peter and Dave's Consulting and Security?

I'll put the marketplace link in the readme so it's big bold and clickable. Thank you for telling me.

After you've used it long enough to have definite opinions, I would appreciate a review, if you are so inclined.

**Comment by byronwall** [comment]
I figured it out eventually.  I thought maybe you hadn't gone through the trouble of listing it, but then I couldn't find a VSIX.  Maybe that link will help the next poor soul who needs to print their TODO list.  I left a 5 star review.  It was a step above the previous printing extension on the first go.  Thanks
