### ISSUE TITLE
Markdown images broken when printing

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#37]
Image tags are being rendered like this
```<img src="vscode-resource:/k:/vsc-print-issue-21-22/2158834-45134090-2560-1440.jpg" alt="img1" class="loading" id="image-hash-64bad7066047e1a71e0a8e1cc6a0738184d1129cec062fb16a0067a0acb8fd96">```

This is probably a consequence of the change to using VS Code's internal markdown rendering pipeline.

**Comment by PeterWone** [comment]
0.7.9 imposes further URL rewriting back to HTTP supported by updates to the embedded webserver.

**Comment by ac-webdesign** [comment]
> 0.7.9 imposes further URL rewriting back to HTTP supported by updates to the embedded webserver.

Thanks it works.

**Comment by PeterWone** [comment]
Once again I thank you for helping me maintain a high standard.

I am developing a non-free version that includes most of the [extensions for markdown-it](https://github.com/search?q=markdown-it) which is the markdown engine used internally by VS Code.

These add support for things like tables of contents, footnotes and LaTeX markup for mathematical notation.

If you are interested in testing this and providing feedback and feature requests, you can let me know privately by mail to peter.wone@outlook.com and I will provide you with the setup kit.
