### ISSUE TITLE
Colons didn't show correctly

### ISSUE THREAD

**Issue by ac-webdesign** [PeterWone/vsc-print#39]
I noticed that the sign `:` are shown as `COLON`.
Can you explain how that happend?

Example: 
![image](https://user-images.githubusercontent.com/43271236/60871831-db6e9500-a233-11e9-827a-40e22516bf62.png)

Also, I created a test.md for you, to test this error.

[test.zip](https://github.com/PeterWone/vsc-print/files/3371952/test.zip)

**Comment by PeterWone** [comment]
Thanks. 

This is an error in one of my regular expressions. 

When I switched to the internal markdown rendering pipeline it rewrote image paths to include the absolute file path of the image file. On Windows this may include a colon, which is illegal in a url so I escape them as the word COLON and then convert them back to : before using the path.

I use a regular expression to do this. It should only apply this transformation to colons inside URLs but it appears to be happening to all of them. I will fix the problem and release an update.

**Comment by PeterWone** [comment]
Okay, after a lot of tinkering with a regex sandpit and one botched release (0.7.10) I believe 0.7.11 handles images correctly but no longer interferes with colons outside of URLs.

**Comment by ac-webdesign** [comment]
Perfect everything works. Thank you.
