### ISSUE TITLE
Fail to send data to local host after CSS style sheet change

### ISSUE THREAD

**Issue by iruletheworld** [PeterWone/vsc-print#41]
After installation, it worked on the first time. Then I changed the CSS style sheet using the F1 command. Then the browser just keeps loading until time out. Msg on the browser : "This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE"

**Comment by PeterWone** [comment]
Which browser on what operating system? 

Uncheck the `Print And Close` setting, then trigger the failure. In the browser, press F12 to get the dev tools, choose the Console tab and use the browser refresh to reload the failing page. You should see error messages that are more specific about what is failing. Take a screen snap and post it here.

**Comment by PeterWone** [comment]
Don't worry about it. I was testing the changes for #42 when the problem you are experiencing manifested. 

Here's what you'd see if you had the new improved exception reporting.

![image](https://user-images.githubusercontent.com/5498936/61015904-0b9f6a80-a3d1-11e9-8b67-56fa10b3a6a9.png)

It's pretty obvious the extension is doubled. Why? Still under investigation.

**Comment by PeterWone** [comment]
Should be fixed in 0.7.12 but you will need to set the stylesheet again or manually remove the `.css`

If you find that 0.7.12 resolves this issue please close the issue.

**Comment by iruletheworld** [comment]
Tried 0.7.12, working fine so far. Thanks a lot
