### ISSUE TITLE
Wrong page is being selected to print

### ISSUE THREAD

**Issue by CarolynBuck-Gengler** [PeterWone/vsc-print#46]
* Issue type: ?? wrong page printed
* Extension Name: vscode-print
* Extension Version: 0.7.12
* VSCode version: 1.37.1
* Chrome: 69.0.3497.128
* OS: Darwin x64 16.7.0

I am having the same problem as I am having with PrintCode, namely, I have more than one window open in VSC (though all but the one I am working with are minimized), and one of the other windows is being chosen to be printed rather than the tab in the window that is currently selected. 
This does NOT happen ALL the time; I was just going through my minimized windows, and when I maximized them and tried to print different tabs on the windows that had previously been minimized, the correct code shows to go to the printer. But when I go back to the window that originally was the only one visible, I still get a tab from one of the other windows.

I /am/ on a mac and read your caveat, and so I don't know if there should be a difference between Mac and Windows for something like this. (But if there is, it's also in PrintCode. Actually, this bug (feature?) in PrintCode is why I went looking for a solution, and I found your May 19 post on StackOverflow.)
Also, sorry if this report does not have the right format. I am still pretty new to using github (as well as VSC) and have never tried to submit a bug report in it before.

I have a screenshot with VSC showing one set of code (the code I might have wanted to print) as well as the code that was actually selected to print, if that would help.

Since this bug(feature) is in both print extensions, I'm wondering as well if I'm doing something wrong in VSC that makes it think that that other window is the current window (don't know why it should do that, very unintuitive if so--but I'm willing to learn the trick if there is one).

**Comment by PeterWone** [comment]
There's currently no "right" format. It's not a large project and I appreciate any bug report better than "it doesn't work".

I'm relying on VSCode to tell me the active editor window. It seems to me that you've actually found a VSCode bug (which agrees with your observation re PrintCode, we use the same method to get content from the editor) and if we can quantify the conditions and platform on which it occurs, I'll be very pleased to help you submit an issue on the vscode repo.

HAS ANYONE SEEN THIS PROBLEM ON WINDOWS OR LINUX?

**Comment by PeterWone** [comment]
Carolyn, I just had a thought. Try this:

1. Open two windows with different files. 
2. Position them side by side so we can identify them as left and right.
3. Click to put the text cursor in the LEFT editor.
4. Click the print icon of the RIGHT window and observe which file is rendered to the browser.
6. Click to put the text cursor in the RIGHT editor.
7. Click the print icon of the RIGHT window and observe which file is rendered.

I will do this on Windows.

**Comment by PeterWone** [comment]
In the absence of apparent interest and not being able to reproduce the described problem I'm going to close the issue. If anyone has information that would allow me to follow up then please do comment.
