### ISSUE TITLE
Rendered Markdown styling and choose what information to print

### ISSUE THREAD

**Issue by zePanzerfaust** [PeterWone/vsc-print#47]
Used version
VS Code Printing Free 0.7.12
VS Code version 1.38.1

I don't know who where and when markdown styling is applied, but would it be possible to have more control over the printed rendered markdown?

Here is an example of a rendered markdown print with Visual Studio 2019 and Markdown Editor extension
![vs-markdown-editor](https://user-images.githubusercontent.com/14841658/65576392-26b25d00-df72-11e9-9b88-f2febcf8e05b.png)

The same file with this plugin
![vsc-printing-header-table](https://user-images.githubusercontent.com/14841658/65576473-5497a180-df72-11e9-9a35-4eafd2f0e7a7.png)
![vsc-printing-footer](https://user-images.githubusercontent.com/14841658/65576478-56f9fb80-df72-11e9-88ab-4864f4e02b2c.png)

**Comment by PeterWone** [comment]
![image](https://user-images.githubusercontent.com/5498936/65583634-ee873a80-dfc2-11e9-8fed-92ccf081230b.png)
![image](https://user-images.githubusercontent.com/5498936/65583675-fe9f1a00-dfc2-11e9-83b9-247857c7de8d.png)

**Comment by PeterWone** [comment]
Are you satisfied with this as a solution?

**Comment by zePanzerfaust** [comment]
It's sufficient for the header and footer yes, thank you.
Do you also know how to get styling when using a table as in the image? Or underlining a header?
Can I modify a css or something? Or is this css embedded in the code?

**Comment by PeterWone** [comment]
Markdown rendering is done by VS Code, not by the printing extension, and VS Code does support the injection of CSS. There is an example of how to do this in the section concerning KaTeX

    "markdown.styles": [
      "https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css"
    ]

Perhaps I should explicitly call out this information with its own section.

You should also be able to embed CSS directly into your Markdown simply by embedding an HTML <style> block with CSS in it.

**Comment by zePanzerfaust** [comment]
Yeah while relative paths are not the best, embedding css clutters up the content too much.
Maybe VS Code will add some other possibilities in the future.
But thank you for the information that's fine for now.

**Comment by ryanwwest** [comment]
I would like to be able to modify some, but not all, of the header/footer info. Specifically, I want to hide the date and bottom-left 'localhost' text, and include the full filepath (not just the filename) at the top. Is this possible? I can make a new issue if that would be better.

**Comment by PeterWone** [comment]
@ryanwwest yes it would be better to open a new issue. 

Actually implementing this is problematic, but I understand why you would want it. After you create the issue I'll explain why it's harder than it looks and how I think I might go about it.

**Comment by PeterWone** [comment]
@ryanwwest I just re-read your message and you may be able to achieve your goals which are not as difficult as full control of headers and footers. I'll expand when you open the issue.

**Comment by ryanwwest** [comment]
Thanks. See https://github.com/PDConSec/vsc-print/issues/163.
