### ISSUE TITLE
Local images break with vscode 1.39

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#48]
Local image paths work in preview, but not in the browser when printing. 

VS Code is reporting the path differently. Need to rewrite the regex.

Thanks @ac-webdesign

**Comment by PeterWone** [comment]
@ac-webdesign 0.7.13 should resolve the issue.

**Comment by ac-webdesign** [comment]
> @ac-webdesign 0.7.13 should resolve the issue.

Thanks it works.
