### ISSUE TITLE
Support for WSL (enable to run locally / remotely)

### ISSUE THREAD

**Issue by rogererens** [PeterWone/vsc-print#51]
This is a request/idea for additional functionality.

Using [WSL2 ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) (Windows Subsystem for Linux) as development environment, installing your plugin puts it in the WS:UBUNTU - INSTALLED category (Ubuntu is the Linux distribution I use).

However, there is no browser installed in Ubuntu.
Enabling an alternative browser and choosing
_"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"_
as its path seems not to start up a browser AFAICT.

Therefore I would like to have your extension installed in the category LOCAL - INSTALLED.

The VSC WSL docs mention the possibility to choose where to run an extension if it supports it:
https://code.visualstudio.com/docs/remote/wsl#_advanced-forcing-an-extension-to-run-locally-remotely

**Comment by PeterWone** [comment]
@rogererens WSL is a bit outside my experience. But if you know how to do this then I'd be more than happy to merge a PR .

**Comment by rogererens** [comment]
I'm a WSL novice as well, so no PR coming from my side any time soon, sorry!
I guess the extension should detect it's in WSL land, and call a browser executable in Windows land.

A work-around might be to install a browser in WSL, and an X-Window server (e.g. Mobaxterm) in Windows. I cannot test that right now because I'm on a PC with limited disk space, and had to remove WSL :-(

**Comment by sburlappp** [comment]
I added this to my local Windows settings.json and now remote file printing works great:

    "remote.extensionKind": {
        "pdconsec.vscode-print": ["ui"]
    }

Please update your package.json accordingly:

https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds

**Comment by PeterWone** [comment]
@sburlappp thank you very much for this small but quite valuable contribution. If you would like to be formally credited, bang up a PR. Otherwise I can add this in myself as you have suggested.

**Comment by sburlappp** [comment]
Please go ahead, don't let me hold things up.

**Comment by PeterWone** [comment]
The delay was mostly because I didn't want to push an update on everyone for a config change easily applied manually. But a bug was report so I've rolled out updated contributions including your suggestion. If it tests ok then please confirm this by closing the issue.

**Comment by PeterWone** [comment]
@sburlappp sorry I forgot to mention you in my last post here. Do you think you could test whether this release correctly configures per your suggestion?

**Comment by PeterWone** [comment]
In the absence of positive feedback I can only assume that silence is golden. 

If anyone else has trouble with WSL please let me know.
