### ISSUE TITLE
Font family for printing is locked

### ISSUE THREAD

**Issue by trdischat** [PeterWone/vsc-print#54]
The printout is not respecting the font selected in 'Editor: Font Family'.  Looking at the source code for this add-on, it looks like it is hard-coded to use Consolas at all times.

**Comment by PeterWone** [comment]
You are right. I marshalled the editor config and used the tabSize but forgot to change "Consolas" to "${editorConfig.fontFamily}". 

I've applied this change in my local repo and there's a config change to better support WSL that I also need to roll out so after I find that there will be a new version.

I'm surprised no-one has previously commented; it should have been `monospace` to work cross platform.

**Comment by trdischat** [comment]
I really love Fira Code.  So it kinda stuck out in the print preview.

I reviewed the page source from the printout page in Chrome and noticed that the font-family was stuck on Consolas no matter what I changed in my settings.  So I dug around in your code and figured out that it was hard-coded that way.

No rush on the fix.  The printouts look great already. :smile:

**Comment by PeterWone** [comment]
The no-rush fix is in the marketplace along with appropriate config to support WSL (a user contribution that has been waiting for an update to happen). 

Would you be so kind as to update test and then either report my abject failure or confirm full function by closing this issue?

**Comment by trdischat** [comment]
Font family from the editor is passing through to the browser perfectly.  Thanks.

**Comment by PeterWone** [comment]
Thank _you_. This is what open source is all about.

After you've used it for long enough to have definite opinions, please consider writing a review.
