### ISSUE TITLE
Local images broken

### ISSUE THREAD

**Issue by adrian-cerdeira** [PeterWone/vsc-print#64]
Local image paths work in preview, but not in the browser when printing.
Example:
![image](https://user-images.githubusercontent.com/43271236/92241686-ec11ae00-eebe-11ea-98fa-36a658a24aa1.png)

**Comment by PeterWone** [comment]
You are observing correct behaviour in preview so we can be sure the path to the image is valid, and it is transformed correctly for preview but not for the browser. To help me troubleshoot this, please 

1. Search your settings for Print and Close and remove the tick mark. This will render to the browser but it won't open the print dialog. This gives you an opportunity to examine the generated page.
2. Induce the problem and inspect the broken image to determine the path that's being used by the HTML.
3. Tell me the true path to the file and the path that is rendered into the HTML.

**Comment by PeterWone** [comment]
If you installed from the marketplace you should get an update shortly. It tests ok for me but as usual I'll wait for you to close the issue.

**Comment by adrian-cerdeira** [comment]
It works. Sorry for waiting
