### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jorge3366** [PeterWone/vsc-print#65]
- Issue Type: `Bug`
- Extension Name: `vscode-print`
- Extension Version: `0.7.15`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by PeterWone** [comment]
Jorge, you didn't paste the details. The only thing I know is you experienced some kind of problem. It's not enough information to help you.

**Comment by PeterWone** [comment]
In the absence of problem details I cannot pursue this incident. Feel free to re-open it with actionable data.
