### ISSUE TITLE
syntax highlight code is well presented, but fails to serve

### ISSUE THREAD

**Issue by xetum** [PeterWone/vsc-print#66]
Codium
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-14T03:45:36.707Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-118-generic

Works well when sent to a pdf

**Comment by PeterWone** [comment]
If you can print to PDF then clearly content is being served to your browser.

What do you mean by "fails" to serve? What exactly were you expecting to happen that did not happen?

**Comment by xetum** [comment]
I'm using codium 1.42.2 and ubuntu 18.04. If I print to pdf and then from a pdf viewer (p.e. evince) I print, it works well. Printer is well configured. But if I print directly it just does nothing

**Comment by PeterWone** [comment]
Thanks
