### ISSUE TITLE
Pressing F1 to get help actually results in errorcode 

### ISSUE THREAD

**Issue by Neohiro79** [PeterWone/vsc-print#68]
TypeError: Cannot read property 'replace' of undefined
at escape (c:\Users\XXX.vscode\extensions\pdconsec.vscode-print-0.7.15\node_modules\highlight.js\lib\highlight.js:63:18)
at Object.highlightAuto (c:\Users\XXX.vscode\extensions\pdconsec.vscode-print-0.7.15\node_modules\highlight.js\lib\highlight.js:625:14)
at c:\Users\XXX.vscode\extensions\pdconsec.vscode-print-0.7.15\out\extension.js:231:33
at Generator.next ()
at fulfilled (c:\Users\XXX.vscode\extensions\pdconsec.vscode-print-0.7.15\out\extension.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by PeterWone** [comment]
@Neohiro79 Could you be slightly more specific please?

* What kind of file was in the active editor when you pressed `F1`?
* Where was the focus?

**Comment by Neohiro79** [comment]
I just opened a new tab and wrote some pseudo code, i.e:
p {} 
nothing special - no code at all.
Focus was in the last line - and file not saved at all.

**Comment by PeterWone** [comment]
So is this right? (I'm trying to reproduce it as you can imagine)

1. Open a new file (Ctrl+N)
2. Type `p {}` followed by the Enter key
3. Press `F1`
4. An exception should occur

**Comment by Neohiro79** [comment]
Correct.

**Comment by Neohiro79** [comment]
You can type whatever you want - at least on my machine - it will trigger the error.

**Comment by Neohiro79** [comment]
I type F1 - then "printing: print" - then the browser poppt up with this message - I might not do it correctly.

**Comment by PeterWone** [comment]
As my earliest user I'm sure you realise I'm not copping out when I say it doesn't do that on my machine. 

I have Win 10 (build 2004) and VSCode 1.50.1,  how about you?

I know you have the latest version of the extension from the error message you posted.

Possibly something is corrupted on your machine. This can be the very devil to fix if the corruption is in your extension download cache because VSC will keep getting it from there until I publish a later version.

**Comment by Neohiro79** [comment]
I've the 'same' setup (close) - Winver 1909 - build 18363 - 64 bit an VSCode 1.50.1 - Chrome 83.0.4103.122 and Node.js 12.14.1

**Comment by PeterWone** [comment]
I wish we had a way to ask other users whether they can reproduce this. I've thought about putting telemetry in the extension but people getting  weird about that, they call it spying on them. Maybe I could make it off-by-default and on first time use pop a message telling them that if they have a problem they should turn it on and trigger the problem so as to report heaps of debug info.

**Comment by Neohiro79** [comment]
We can do the following: anyway I need to upgrade my machine the next weeks to the latest windows version, since the whole f*up with Windows Updates I cannot get the latest Windows Version right now. I also have another SSD in my PC with a newest windows version. I'll try to install VSC the next days on this installation to ensure that it is a "blanc state" and try it again.

It might also be another extension which makes troubles, since I've installed a bunch of them.

Originally I just wanted to see what the help says when pressing F1. :-)

**Comment by PeterWone** [comment]
VSCP is bug free! I must find it and KILL IT! :)

**Comment by Neohiro79** [comment]
Yeah, that might be good idea - you can also make a "development-edition" which someone can install - in that case you can be sure that noone is pissed off, since he or she has the "choice".

**Comment by Neohiro79** [comment]
:-) :-)  I know how it feels ... I've the same expectation on my own projects, running me crazy from time to time.

**Comment by Neohiro79** [comment]
I'll try it out and make a reboot, so I can tell you in a few minutes - give it a take or so, hopefully.

**Comment by Neohiro79** [comment]
**Peter, I got the 'same' or 'similar' error on a blanc new windows installation (2004)**

 ```
Error: Cannot access undefined.
 undefined
	at c:\Users\XXX\.vscode\extensions\pdconsec.vscode-print-0.7.15\out\extension.js:143:27
	at Generator.throw (<anonymous>)
	at rejected (c:\Users\XXX\.vscode\extensions\pdconsec.vscode-print-0.7.15\out\extension.js:6:65)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
But I realised this: pressing F1 results in the "top-bar-console" or however they call it, and I had to type "printing: print" to get this error message. But it might be the wrong way to get to the "helpdesk" of the extension.

Since it is an "undefined" error - what if the "parameter" is just "null" or "undefined" - meaning that this console "call" of "printing: print" needs the parameters to "print" - just as the click to the printing-icon I assume. Maybe that's the problem - just a thought

**Comment by PeterWone** [comment]
1. I can reproduce this one
2. You are correct, in VS Code the `F1` key does not request context sensitive help, it opens the Command Palette. Here is a guide to default key mappings. https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
3. I think you are on the right track with your hypothesis.

**Comment by Neohiro79** [comment]
Jesus. Hope you will find the fix for this.

Redarding closing the new issue I predict this: they will tell you "you can fix this if you want", then close it or keep it open like the other one to send all others regarding this issue to this very topic and then sutting them off once they try to talk about it - so prepare yourself for a new extension called "enable proper F1 help in VSCode" - and you're fine. **How dare you to complain.** :-)

**Comment by Neohiro79** [comment]
It's a feature - not a bug.

**Comment by PeterWone** [comment]
The question of whether VS Code ought to be CUA compliant is now moot; it now so dominates the market that it constitutes a standard in its own right. Add to this the fact that it supports user-defined keymaps but nobody remaps F1 back to help, and the argument for compliance is not compelling.

All that said, you _did_ find a bug &mdash; a very subtle one &mdash; and I have finally fixed it. You'll see it in the next release.

**Comment by Neohiro79** [comment]
Hey Peter,

thanx so much for this feedback! I guess I still have to wait for the update then 👍 

Thank you for your honest feedback and continous engagement in this regard!

The very best!
