### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by elsebih** [PeterWone/vsc-print#69]
- Issue Type: `Performance`
- Extension Name: `vscode-print`
- Extension Version: `0.7.15`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Sebas\AppData\Local\Temp\pdconsec.vscode-print-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[pdconsec.vscode-print-unresponsive.cpuprofile.txt](https://github.com/PeterWone/vsc-print/files/5531095/pdconsec.vscode-print-unresponsive.cpuprofile.txt)

**Comment by PeterWone** [comment]
VSC Print uses your browser to render to your printer. When you already have other tabs open in the browser, the **entire CPU load of the browser** is attributed to VSC Printing, causing VSCode to report high CPU usage.

Does this problem occur when you don't have other tabs open? 

If the answer is yes then there is a genuine problem. In that case, I hope you will provide the file that you forgot to attach to this issue: `c:\Users\Sebas\AppData\Local\Temp\pdconsec.vscode-print-unresponsive.cpuprofile.txt`

Either way, I hope you will check whether the apparent high CPU usage occurs for a browser servicing only VS Code, and share the outcome with the rest of the world.

**Comment by PeterWone** [comment]
Documentation for this error report suggests that it can also be a consequence of the need to load a large number of files. Since VSC Printing does depend on libraries that themselves have a large number of dependencies, I will look into bundling for the next release.

**Comment by PeterWone** [comment]
Man, that was a mission. Webpack doesn't like `vscode-nls` or `portfinder` so in addition to general webpack headaches I also had to rewrite without vscode-nls in the run-time dependencies, and totally removed portfinder instead completely delegating port selection to the host operating system. So now there are fewer settings, it's smaller and faster, _and_ it's bundled which should eliminate the high CPU warning on systems equipped with spinning rust (mechanical hard disks).

The release isn't out just yet, I'm still testing.

**Comment by PeterWone** [comment]
0.8.0 addresses this and has just hit the marketplace.

**Comment by elsebih** [comment]
> 
> 
> VSC Print uses your browser to render to your printer. When you already have other tabs open in the browser, the **entire CPU load of the browser** may be attributed to VSC Printing, causing VSCode to report high CPU usage.
> 
> Does this problem occur when you don't have other tabs open?
> 
> If the answer is yes then there is a genuine problem. In that case, I hope you will provide the file that you forgot to attach to this issue: `c:\Users\Sebas\AppData\Local\Temp\pdconsec.vscode-print-unresponsive.cpuprofile.txt`
> 
> Either way, I hope you will check whether the apparent high CPU usage occurs for a browser servicing only VS Code, and share the outcome with the rest of the world.

Hi. First of all, thanks for your time!

I updated the last comment attaching the file required. The problem persists even though without having any tabs opened.

**Comment by PeterWone** [comment]
@elsebih have you updated to 0.8.1, and if so does it resolve the problem or are you still experiencing high CPU use?

I have never personally experienced this, but you are not the only person to report it.

**Comment by elsebih** [comment]
> 
> 
> @elsebih have you updated to 0.8.1, and if so does it resolve the problem or are you still experiencing high CPU use?
> 
> I have never personally experienced this, but you are not the only person to report it.
> 
> Looking through the cpu profile you supplied I see that highlight.js (one of my dependencies, it does the syntax colouring) is responsible for an incredible number of file accesses. This makes me optimistic that webpack will resolve the problem. It seems likely that the reason I don't get the problem is that on my system these files are on a high performance SSD with zero seek time and zero latency, so lots of small files aren't a big problem.

Yes, I updated to 0.8.1 before attaching the .txt file, so the error persists. Hope you know how to deal with it! 😃

**Comment by PeterWone** [comment]
From the file you attached:

```
url": "file:///c:/Users/sebastian/.vscode/extensions/pdconsec.vscode-print-0.7.15/out/extension.js",
```

That file was generated by 0.7.15 which is the previous release. 

I'll leave the issue open for a while. Let me know if you get the problem again.

**Comment by elsebih** [comment]
> 
> 
> From the file you attached:
> 
> ```
> url": "file:///c:/Users/sebastian/.vscode/extensions/pdconsec.vscode-print-0.7.15/out/extension.js",
> ```
> 
> That file was generated by 0.7.15 which is the previous release.
> 
> I'll leave the issue open for a while. Let me know if you get the problem again.

I don't know why it was generated with 0.7.15 if I am using 0.8.1. The issue popped up in VS Code when I was actually using the 0.8.1 VS Code Print version.

**Comment by PeterWone** [comment]
It may help to remove that file from your system. You have a copy here if you want to refer to it.

Are you experiencing reports of high CPU usage every time you use it or just occasionally?

**Comment by PeterWone** [comment]
You can manually inspect. 

1. Close all instances of VSCode and start with code --inspect-extensions=9993 or any other port number.
2. Execute the `Developer: Show Running Extensions Command`. This command opens an editor with all the running extensions.

![image](https://user-images.githubusercontent.com/5498936/99023753-f7651200-25b0-11eb-9d0f-1d46602695f8.png)

As you can see, on my system vscode-printing took 22ms to activate. I ran this a few times and got numbers ranging from 21 to 85ms. For comparison, on the same system with the same memory pressure (same inspection) the Javascript debugger took 137ms.

22ms is shit hot and 85ms isn't horrible. I am flummoxed as to why you should be experiencing this. I had a good look at my activate method and I haven't done anything boneheaded like synchronous file reading.

**Comment by PeterWone** [comment]
How many cores does your CPU have?

**Comment by joshgoebel** [comment]
> Looking through the cpu profile you supplied I see that highlight.js (one of my dependencies, it does the syntax colouring) is responsible for an incredible number of file accesses. This makes me optimistic that webpack will resolve the problem.

[Highlight.js maintainer here]  Not sure that's your problem - unless it's a VERY slow hard drive.  But yes you could use webpack to bundle us somehow... but we also have a build process... so you could download the source from GitHub, and build a "browser" build (which should also be easily made to work with a plugin) and then you'd have everything in a single JS file.  You can also control the size precisely if you throw out a few large languages that no one is probably using.  Using all 190 is probably overkill.

**Comment by PeterWone** [comment]
@joshgoebel I wasn't really blaming highlight.js

* I've never experienced the problem on my modestly resourced workstation.
* Before I bundled it was effectively load on demand from a local cache. 
* Bundled, the whole damn thing is about the same size as jQuery.

I bundled because that was the explicit advice on the page linked from the "error" report. I've had two such reports in two years. Presumably there were more, but nobody ever reported "I keep getting this annoying message" and I'm still waiting to see it myself. I pondered what configuration might suffer most from a lack of bundling and the answer is spinning rust and single core.

I understand the strategy you are proposing. The weakness is a dependence on internet connection being available at all times. VS Code is frequently used on notebooks which move between networks and are often disconnected while in use.

Admittedly attempts to print usually occur in locations like the home or workplace because that's where the printers are, so your proposition could work for the main case, but it would fail on isolated networks which are common in secure areas like coal mines and oil rigs.

**Comment by joshgoebel** [comment]
I feel like perhaps we're talking past each other.  I'm not talking about WHERE the file is, only how our source is stored.  At a glance I looked at the logs and saw it loading individual files.  We have 190+ separate JS files.   Perhaps on a spinning disk poorly fragmented under load that could be a bottleneck.  You *could* ship instead a single large file (which disks are typically usually able to load much faster).

That file would still be local, on disk, part of your extension.  None of this has anything to do with local vs remote.

It's just about whether you ship 190 files vs 1 single JS file.

**Comment by joshgoebel** [comment]
Or you could decide this is an edge case and just not worry about it. :)  I agree it's hard to fix things you can't test yourself.

**Comment by PeterWone** [comment]
> Note: I have little familiarity with VS Code extension internals and how they are stored on disk... I presumes though that's it's a bundle of files... so that Highlight.js could be part of that either in multi-file or single-file form.

Loose files are installed from a VSIX file which is basically a zip file with a manifest. If you use webpack then the node_modules tree becomes a bundle. The installer is oblivious to the difference.

**Comment by joshgoebel** [comment]
> If you use webpack then the node_modules tree becomes a bundle.

I was merely saying there is "middle ground".  If you *built us from source* (not npm) you could build us as a single file... then just throw us into your repo as a vendored asset, etc... though that makes updating slightly more annoying.  So the only part of your project that would be "packaged" is us - saving you setting up a whole build pipeline you may not need.

Though you're left with no auto-mated way to update the dependency... so maybe that's not the greatest idea..

**Comment by PeterWone** [comment]
Right, ok. By the way, I really appreciate your insights.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PeterWone** [comment]
No-one has reported this for months. Seems to be sorted.
