### ISSUE TITLE
Request to integrate the link to manual.md into the command palette via Printing: Manual

### ISSUE THREAD

**Issue by Neohiro79** [PeterWone/vsc-print#70]
Hey Peter, I finally got your nice smooth update :-)

I realised, that the original issue, having to "search" for "how to get the f* manual" of your extension got completely lost.
However, I could find a link in your plugin description to this site: 

> https://github.com/PeterWone/vsc-print/blob/master/manual.md

While we know now that pressing F1 won't show up the help inside VSC at all - but the command palette - is it possible to make an integration of this specific "helpdesk-link" - or even better opening the .md-file itself inside VSC as tab when typing `"Printing: Manual"` into this command palette?

After Pressing F1 right now this command palette only shows `Printing: Browse for stylesheets` and `Printing: Print` (which triggers the print dialog now perfectly)

---

As a nice side-effect you could write an article someday :-) `about how to properly integrate a helpfile into VSC extensions`, which might help a lot VSC extension developers or users out there in the future - if there isn't any of this already implemented 'somewhere'.

---

You could even implement a specific "extension-helpdesk" icon if you have time to do so (like you did with the print-icon) in this topbar of VSC where ALL extension-developers could "push" their specific extension-helpfile.md into via a special API-call to your extension.

When clicking on that icon, you would see / be able to search for your specific "extension-name" by typing it in or choosing just like it is realised in the command palette right now - then opening this specific helpfile.md as tab ...

Just some thoughts, no bugs :-) ...

**Comment by PeterWone** [comment]
The  biggest issue with presenting documentation via a palette command is nobody is expecting it so no-one would look for the manual that way until after they already read the manual, which somewhat defeats the purpose.

That said, it’s a damn fine idea to establish this as a convention. I’m going to give it some thought.

Here are some possibilities that come to me right off the cuff:

  *   Re-instate the CUA meaning for F1, and bind Shift+F1 or F4 to the command palette (neither are in use, I checked)
  *   Help can be HTML in a browser or markdown in the preview pane
  *   Could be on the web or local files
  *   To the extent that context can be determined, provide context sensitive help the way apps did in the golden era of Windows.
  *   With a clearly defined convention, extensions could contribute contexts and related topics and content

Remapping keys is easy, it doesn’t even require code, it’s just an entry in the contributions section of package.json, but some people won’t like it so it would have to be a setting defaulted to off.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Neohiro79** [comment]
In that case I might think it would work better with the icon, when "pressed" it just opens up my help and that's it. 

The conventions they use are what they are - they just use them, and we have to deal with them.

I personally would've either tried to find "somewhere" the hint to the manual or description of the plugin than thinking about pressing F1. But if I do - I will immediately see the "command-palette" then "extension name: help" and can just 'go' there.

I'm completely fine with this - no remapping or whatsoever needed. 

Just a new entry for the extension for this command-palette and an icon to press and see the results.

What can one potentially ask more ;-)

**Comment by PeterWone** [comment]
@Neohiro79 so what do you think? The options are

* Spawn a browser loading the rendered manual
* Open the markdown in a markdown preview pane

I think spawning a browser is more convenient for multi-monitor setups, but it's more complex to set up since I'd need a way to inhibit the inclusion of the script that shows the print dialog and closes the browser tab after printing.

Preview pane can be done quickly, browser version is in my opinion better but will have to wait for me to have time, probably months.

**Comment by PeterWone** [comment]
Update your repo and run the extension in debug mode to try this in 0.8.4 which is not released on the marketplace.

If you want to install it as though it were packaged and published then 

1. pull the code 
1. open it in VS Code 
1. run `npm i` in the vscode console 
1. run `gulp package` in the vscode console 

This will produce a VSIX that you can install using the ellipsis button in the extensions pane of vscode.

**Comment by Neohiro79** [comment]
So basically, if I donwload the whole repo as zipfile and unzip it into the extension folder of VSC it does not work from startup?

How do I enable this debug-mode again to make it work?

**Comment by PeterWone** [comment]
1.  Get the clone URI onto your clipboard (just click the clipboard button next to it) or copy from here https://github.com/PeterWone/vsc-print.git
[cid:image001.png@01D6C32A.5831CDB0]
  2.  In VS Code press F1 and type CLONE
[cid:image002.png@01D6C32A.EB747910]
  3.  Press Enter to get this
[cid:image003.png@01D6C32B.248081E0]
  4.  Paste the URI https://github.com/PeterWone/vsc-print.git and press Enter
  5.  A file dialog will open, tell it where you want the repo
  6.  Open the repo in VS Code
  7.  Open the VS Code Terminal pane
  8.  Type `npm i` then press Enter
  9.  Type `gulp package` then press Enter


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PeterWone** [comment]
1. Get the clone URI onto your clipboard (just click the clipboard button next to it) or copy from here https://github.com/PeterWone/vsc-print.git
![image](https://user-images.githubusercontent.com/5498936/100178238-3f742500-2f1f-11eb-9fc0-545c8502d650.png)
2.	In VS Code press F1 and type CLONE
![image](https://user-images.githubusercontent.com/5498936/100178359-721e1d80-2f1f-11eb-8a29-527e923c298d.png)
3.	Press Enter to get this
![image](https://user-images.githubusercontent.com/5498936/100178387-7cd8b280-2f1f-11eb-8c40-d81f9ffd78df.png)
4.	Paste the URI https://github.com/PeterWone/vsc-print.git and press Enter
5.	A file dialog will open, tell it where you want the repo
6.	Open the repo in VS Code
7.	Open the VS Code Terminal pane
8.	Type `npm i` then press Enter
9.	Type `gulp package` then press Enter

**Comment by PeterWone** [comment]
Don't worry about the vulnerabilities. They apply in a web page in a browser, which this isn't.

**Comment by Neohiro79** [comment]
Thank you so much for this desciptions. 

It first didn't work as described, since I don't need to press enter after `clone` (else it wanted me to login to my git account, saying no repositories found since there aren't any yet)

**It worked till the gulp-package at least:**

![npm-result](https://user-images.githubusercontent.com/18111492/100179252-e338e300-2ed5-11eb-83d0-843777b38714.jpg)

**The problem with gulp (maybe missing something - install something more here?)**

![gulp-result](https://user-images.githubusercontent.com/18111492/100179260-e59b3d00-2ed5-11eb-94c9-a875b4cefaa5.jpg)

**Comment by PeterWone** [comment]
You need to install the gulp CLI

`npm i gulp-cli -g`

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Neohiro79** [comment]
It worked! 👍

**Comment by PeterWone** [comment]
See updated instructions. You need the gulp-cli
```
npm i gulp-cli -g
```

**Comment by PeterWone** [comment]
Here's your chance to contribute to the codebase. Fork the repo so you can check stuff into your own fork, then add gulp-cli to the devDependencies section of package.json with 

```
npm i gulp-cli --save-dev
```

then check it in and push it to your fork

then create a pull request and I will add it to the master repo

**Comment by Neohiro79** [comment]
> This will produce a VSIX that you can install using the ellipsis button in the extensions pane of vscode.

**I didn't see any of this `ellipsis` button you were talking about. so I also tried F5.**

So after F5 is pressed a new VSC window popps up, but when I open a file and press F1 there is no icon or helpfile opening up - do I need to be in a specific folder or have a specific file open to see the changes

![gulp-compiled-successfully](https://user-images.githubusercontent.com/18111492/100180130-d2896c80-2ed7-11eb-8607-524e066e5146.jpg)

**Where do I find this `ellipsis button`?**

**Comment by PeterWone** [comment]
![image](https://user-images.githubusercontent.com/5498936/100180349-af84aa00-2f23-11eb-9c33-b036866c0c76.png)

**Comment by Neohiro79** [comment]
![looks-like-this](https://user-images.githubusercontent.com/18111492/100180347-3e6bd500-2ed8-11eb-903c-75daeaa09948.jpg)

**Comment by Neohiro79** [comment]
It's the wrong extension, your's isn't even in there.

**Comment by PeterWone** [comment]
The VSIX is generated in the project folder. Copy the path.
![image](https://user-images.githubusercontent.com/5498936/100180601-39cd0e00-2f24-11eb-9f63-75467aed58bd.png)

**Comment by Neohiro79** [comment]
Oh - ok. Worked! I've found and `installed` the VSIX file: 

![got-the-visix](https://user-images.githubusercontent.com/18111492/100180545-a9b5a700-2ed8-11eb-92fa-c1852836dd6c.jpg)

Now how do I see the changes?

**Comment by PeterWone** [comment]
I see you speak German. (Well I think it's German. I can't read it.)

Are you interested in maintaining the German UI translation? 

I have no further time today but I can walk you through it. Basically you get the English file side by side in your editor and update the entries to add new ones with the German translation, and delete any that aren't in the English version.

That and the translations for the manual and the other docs.

**Comment by Neohiro79** [comment]
Yeah. Basically that's the normal language here in Germany :-)
Thanx to god I am also used to the english language - which I like much more.

Yeah, sure. If it's only one or some file(s) no problem.

But I need to figure out how this whole git-process of fetch, fork, push, pull, pull-request and whatever funny things works ...

**Comment by Neohiro79** [comment]
Do I need to add another command or can I close VSC without loosing this "VSIX" installation in VSC or whatever that is?

**Comment by PeterWone** [comment]
If you installed from a VSIX it's permanent, if you run in the extension host it isn't.

**Comment by Neohiro79** [comment]
Yeah, I did as you described - searched in the local repo and chose this ".vsix" container file.

**Comment by PeterWone** [comment]
A VSIX does the same as installing (or updating) from the marketplace.

For a given language the work items are

* Manual
* Change log
* Readme
* UI strings

The manual and readme don’t change much. The change log gets a new entry for each release which also appears in the readme (copy it) and as you know the extension is mature so there’s only a few per year.

**Comment by PeterWone** [comment]
Congratulations, you built and installed an OOB release (out of band).

**Comment by Neohiro79** [comment]
:-) Yeah, I will look into it then send them to you once I've found them. I guess I first need to figure out how this clone and pull / request whatever shit works to send them to your repo.

**Comment by Neohiro79** [comment]
> Congratulations, you built and installed an OOB release (out of band) from a repository.

Thanx to you perfect guided tour and descriptions! 👍

**Comment by PeterWone** [comment]
For someone fluent in both languages and equipped with the right keyboard for the target language it's a half hour job tops. 

I will walk you through it some other time. I am way too busy for any more today. If you have skype we can screen share and get you set up. If you take on the German translation then the most complex parts of the setup only need doing once and then you make changes to the same clone on your computer and push to the same fork and creating a PR is the same every time.

The worst mistake you can make is leaving out a comma and I don't need to read German to find and fix that.

**Comment by Neohiro79** [comment]
Here is my contact address:

http://pastie.org/p/2CzM95n5u2gQetizxL3VFb

:-)

**Comment by Neohiro79** [comment]
With JSON I am familiar, so there's nothing to worry about from that end, only Git and it's `frankenstein-api` is something I've tried to avoid to use till today ...

**Comment by PeterWone** [comment]
I'm sure you are familiar with JSON but it's easy when pasting updated content to accidentally lose a closing quote. Happens to me all the time patching the French version. I slap the English into Bing translate which unlike me always gets conjugation and number agreement right, plus it puts in all the accents which are a pain to type on a US English keyboard. Then I proofread the translation, laugh about stupid machines, fix it and copy/paste into the corresponding entry in the French file. It's convenient but slight mouse selection errors can easily clobber a closing quote or put one too many in.

Even though I am capable of manually rewriting the translation I usually do it by rewriting the English version to make it less ambiguous, because this is usually an improvement to both. 

Often machine translators fail because they are unable to use _a priori_ subject knowledge to narrow interpretation. Rewriting to remove the dependence on implicit context is always a good idea so I guess you could say I'm using a machine translator to do static analysis of natural language.

**Comment by PeterWone** [comment]
@Neohiro79 are you happy that this issue is dealt with and ready to close?

**Comment by Neohiro79** [comment]
@PeterWone if you talk about this very issue here to "open the manual" (which it does perfectly well now), yes, superb!

Ready to close :-)

![printing-manual](https://user-images.githubusercontent.com/18111492/123187591-c0d26c80-d49a-11eb-8981-2a080add01cf.jpg)
