### ISSUE TITLE
Please consider upgrading your Highlight.js dependency.

### ISSUE THREAD

**Issue by joshgoebel** [PeterWone/vsc-print#71]
The version you are using is very old and contains several "freeze" (infinite loop) issues as well as numerous security vulnerabilities (ReDOS attacks, etc)... I'm not sure if VS Code does anything to mitigate the ReDOS type issues (what Regex engine they are using)...

Would highly recommend you upgrade to the latest v10 release.  We just dropped support for v9 entirely the other day and it hasn't really been maintained since April when v10 was released.

**Comment by PeterWone** [comment]
I have no objection to that. I'll update to the latest release and do a smoke test. 

As for redos or other toxic input, we are essentially taking source code and colourising it before wrapping it in an HTML page and serving that to a browser on the same workstation so that the browser can print it. 

If people have poisonous source code of doubtful provenance they have way bigger problems than print jobs that freeze.

**Comment by joshgoebel** [comment]
> As for redos or other toxic input, we are essentially taking source code and colourising it before wrapping it in an HTML page and serving that to a browser on the same workstation so that the browser can print it.

Good point - and that's a huge distinction for sure.  **But this can happen accidentally as well.**  That's often how it's reported to us actually - users accidentally trying to highlight the exact wrong piece of code that triggers one of these types of bugs - no malicious intent.

Worst case it could lock up someones VS Code or crash it (I'm not familiar enough with their model to know).  Perhaps the plugins are all in isolated processes - in which case you could just set someones CPU on fire maybe. :)

**Comment by joshgoebel** [comment]
> If people have poisonous source code of doubtful provenance they have way bigger problems than print jobs that freeze.

Also a thought:  I routinely open and browse "random" code from various project using VS Code.  I would not expect that code to be able to maliciously affect VS Code in any way. :-)  So I don't think you can assume anything anyone wants to print is "safe". :)

**Comment by PeterWone** [comment]
The plugins _are_ isolated, they run in a thing called the "extension host". This is a pretty normal thing to so when you let third parties write code that runs in the context of your application... but I take your point.

**Comment by joshgoebel** [comment]
> The plugins are isolated, they run in a thing called the "extension host". This is a pretty normal thing to do when you let third parties write code that runs in the context of your application...

Sure, that makes perfect sense.  But I dunno what happens when a plugin goes into an infinite loop or locks up the regex engine with an exponential backtrack... whether you just can't use that plugin anymore - is it ever killed? - does it have any ill effects at all on the rest of the environment... I don't know those things.

**Comment by PeterWone** [comment]
Suggestion implemented. Thanks for your help.
