### ISSUE TITLE
printing reverse colours, white on black, don't have enough black cartridges to support this extension

### ISSUE THREAD

**Issue by phenry-Fusebill** [PeterWone/vsc-print#75]
When looking at what is going to be printed, it's white on black, therefore, the majority of the page is going to be black ink. I can't find any settings to change\invert color. Am I missing something?

**Comment by PeterWone** [comment]
Yes, going by your description you have chosen a dark theme stylesheet. I specifically mention that this is a bad idea because it creates the situation you describe. This is why stylesheet is a setting, instead of dynamically reflecting the stylesheet you choose for VS Code.

Choose a light theme stylesheet.

Why do I ship unusable stylesheets? I ship _all_ the stylesheets bundled with the text colorising library that I use. Every now and then they add new ones and this is how they are included.

**Comment by phenry-Fusebill** [comment]
Thank you for the note. I have a couple of helpful hints for next new users. Take what you want and leave what you don't want. :>

re chosen dark theme
Unfortunately I didn't pick a theme. I installed, and tried to print my code. My VS Code is light, so I assumed I would get what is required\necessary\etc if that was going to be impacting some decision. Furthermore, upon installing again, I cannot see a theme setting in the extension settings (remember, my VSC is already in light theme, I don't expect to go anywhere in VSC to change a theme, it's already light).

re specifically mention that is a bad idea
I'm sorry, but I don't see "theme" anywhere on the pages description, so I'm not sure where you mention this?

re ship with all stylesheets
Thank you, that's cool. Unfortunately I don't know about that. You might want to add something to the front page indicating what or how? Maybe?

These are just ideas. Something to help reduce the initial hiccup, speedbump. For me, I NEEDED to print and since this didn't help me, I didn't have time to go looking for deeper answers past the extension settings. I had no choice but to uninstall and find another which did help (which I did).

Thanks.

**Comment by PeterWone** [comment]
That’s quite surprising, and I do appreciate your bothering to leave feedback. Out of the box it should have used a light theme. It’s certainly designed to. No-one has ever reported a dark theme by default problem, and given the number of users I have and the fact that would be an out of the box fail I can’t imagine how it could go unreported so long. That said I don’t want this to happen to anyone else so I’ll have to look into it when my day job permits.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by phenry-Fusebill** [comment]
Thanks for the reply. Good luck and have a good weeekend.

**Comment by ADBeasley** [comment]
On a Mac,

1. Uncheck the 'alternate browser' check box in the extension settings
2. When presented with the printer dialog **untick** the 'Print backgrounds' check box on the 'Safari' section.

![Screenshot 2021-02-06 at 17 44 05](https://user-images.githubusercontent.com/39886283/107125658-24b91780-68a3-11eb-823b-6b42e1092f01.png)

This will then set the background to white in the preview and the print will not add a background.

**Comment by PeterWone** [comment]
@ADBeasley Thank you for contributing a workaround. 

Can I interpret your contribution as meaning this happens with light themes on a Mac? Is it restricted to Safari?

Not having access to a Mac I am unable to check this myself.

**Comment by ADBeasley** [comment]
Sorry I was not clear - yes it happens on the light theme in Catalina.

**Comment by PeterWone** [comment]
What is the behaviour with other browsers such as Chrome or Brave?

**Comment by ADBeasley** [comment]
No idea :-). I've only got Safari on here at the moment.  I'm happy to try Edge / Chrome for you though over the next week (mental health allowing) if that's OK? 

I'm new to VS Code so I may need a bit of hand holding.

**Comment by PeterWone** [comment]
It's worth having a look at whether your stylesheet sets the background colour. 

I don't know whether Safari supports this but all the major Windows browsers do: if you press F12 you get some tools that let you snoop around the page looking at mark up and stylesheets and network traffic etc.  

Anyway, if you have a direct equivalent to this then in your VS Code settings turn off the Print and Close checkbox.
![image](https://user-images.githubusercontent.com/5498936/107148122-472f5b80-699d-11eb-882e-2c4639ab7e21.png)

Then print something. The browser will open and load the page but it won't open the print dialog or close the browser. This will give you a chance to do the Apple version of pressing F12. What you're looking for is an explicit background colour. Usually the F12 tools let you fiddle with the page; you can see what happens when you do things like set a background color for any element. 

My stylesheet is atelier-light and it sets a light buff background colour _in the browser_ but due to media queries this is white for printing and the print preview.

I wonder whether Safari botches media queries.

**Comment by ADBeasley** [comment]
Using Safari (my default browser) I get get to the source via the developers window - see [Apple KB](https://support.apple.com/en-gb/guide/safari/sfri20948/13.0/mac/10.15) and that gives me:
![Safari Default background](https://user-images.githubusercontent.com/39886283/107151589-483f9900-695b-11eb-84ec-419d1aef7289.png)

and I can edit the HTML to confirm it changes:

![Safari changed background](https://user-images.githubusercontent.com/39886283/107152083-e7fe2680-695d-11eb-9609-2015fa9c0207.png)

Trying to add another browser via your settings is a bit fun.  I loaded Edge as the first trial and pointed the app to use the  executable (/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge) but that did not launch.  On the Mac you have to use one of two methods:

1. Set the default browser to Edge (System Preferences / General / Default Web Browser)
2. Set the path to the actual **.app** container object (/Applications/Microsoft\ Edge.app in this case)

Interestingly f12 in Edge works (the Mac cmd-opt-U shows source only in a separate tab) I see the same style-sheet controlling the background:
![Screenshot 2021-02-07 at 15 39 54](https://user-images.githubusercontent.com/39886283/107151813-87bab500-695c-11eb-8359-3c3cbee3a8f5.png)

I did notice in the default extension settings you have _vs2015_ listed as the style and the comments in the file say this is your _Visual Studio 2015 dark style_ - is this just a default or selected at install time based on the system light / dark settings?

**Comment by PeterWone** [comment]
Looks like you found the problem then. I really couldn't tell you why the stylesheet defaulted to vs2015, that's a crazy choice.  We'll have to fix that up, it's a terrible first experience.

**Comment by phenry-Fusebill** [comment]
Thanks for the due diligence to sleuth this one out. Thanks guys.

**Comment by ADBeasley** [comment]
> Now that this is out in the open I wonder whether it might not be prudent to examine the stylesheet when one is selected and warn the user whenever the background colour is darker than say #e0e0e0
> 
> Or maybe cull them during build.

I think the use of style sheets is the correct thing to do (though I currently have some orange commands in places) but honestly can see zero use of a background colour unless it is to show live vs test code (and I used to use coloured paper / watermark for that).

My preferred way would be for the code to default the background to white overriding any style sheet settings for this. Not as friendly as putting the background colour specifically in the properties sheet of your extension but the call is yours (or a fork if folk really care) :-)

Happy to have helped.

**Comment by PeterWone** [comment]
I'm now debating whether it's worth pushing an update to change a default setting or let it slide till we figure out #76 

While it's trivial (pick a light stylesheet) this is not the first impression I want people to have.

**Comment by ADBeasley** [comment]
If you want to wait how about a note at the top of the documentation for now?

I've never had an extension update on my Mac so have no idea the user impact or how long it takes but I would not be too worried about an update for minor things as I use an iPad and get lots per week! Key thing would be to leave everyone's settings as is.

Do you know how easy it is to access remote code? If it's difficult (or you are time constrained) then a delayed update leaves any new users with the issue and given the remote issue had not been raised till I tried maybe other developers use my workaround?

**Comment by PeterWone** [comment]
Leaving existing settings as-is is the reason I never noticed this. I've installed this extension hundreds of times. Re accessing remote code, never did it, have to learn, no idea yet. 

The problem with "just" updating the docs is that to change the marketplace page I have to push an update with a new version which means a whole build cycle. I can change it on github though.

**Comment by lnlp** [comment]
> Can I interpret your contribution as meaning this happens with light themes on a Mac?

Most of your inluded css files ('Browse for style sheets) with a light theme do _not_ have a true white background but use some off-white background instead. For printing this is annoying because it tries to print the off-white background allover the page.

**Comment by PeterWone** [comment]
Default theme set to better initial value in next release.

**Comment by lnlp** [comment]
My advise would be to either remove all your included style sheets that do not print a true white background. Including any dark themes is useless to include with a plugin for printing, the light ones without true white background should be simple to fix. This is however something that users of the plugin should not have to bother with. Having many style sheets included that provide poor output gives a poor (first) UX that can be easily prevented. Be aware that most users will use the plugin without being aware of its internal workings.
Your plugin is very promising but I have not yet found a style sheet yet that provides the same richness of the syntax coloring in the editor. As alternative for richer syntax coloring I still print my code in NotePad++ is not a preferable workflow.

**Comment by PeterWone** [comment]
Well then maybe I'll have to cull all but a suite of reasonable light stylesheets _and_ force the background to white.

**Comment by phenry-Fusebill** [comment]
Howdy. First off, I feel a bit bad, I can't help but feel I raised this thorny issue. However, it was a previously unknown issue, and now with many-hands, it's been identified and fixed. Fantastic. Second, thank you PeterWone for this functionality, for without, I'm back to CTRL+A, CTRL+C, open Word, CTRL+V, CTRL+P, enter, enter, I think there's one more enter, then ALT+F4...yeah, done it enough to be a PITA. Thank you Peter. And lastly, there's many ways to fix this, I think you're last idea Peter is a good one, with one suggestion to have a link in the extension to allow me to click a link and immediately goto the other webpage showing me the large list of other non-included stylesheets. Maybe even showing me previews, including the installed ones.

All this to say, thank you Peter. I've actually used it a few times since raising this. Thanks.

**Comment by PeterWone** [comment]
Why would you feel bad about raising the quality of the tool? Some people would have given it a bad review and promptly disappeared forever. Even for issues where the answer is RTFM raising an issue can highlight missing or unclear documentation.

I was blissfully unaware that there was a really crappy default. You've improved the out of box experience for everyone.

**Comment by phenry-Fusebill** [comment]
Thank you for the feedback. And the same sentiment back at ya. 👍 Thank you for the extension. :> Many thanks. PS I have to go review it! DOH! :<

**Comment by PeterWone** [comment]
Also, don't be shy about suggesting enhancements. Sometimes they're too hard, and sometimes they sit around till the landscape changes and their time has come. For instance, as a side effect of things I'm doing in my day job, I'm currently looking at supporting a "master document" for markdown so you can break a big document into multiple files. While some people would say Pandoc has done this for years, supporting it directly in VSCode gives you version control per chapter and live collaboration tools... I think this is an idea whose time has come :).

**Comment by PeterWone** [comment]
> My advise would be to either remove all your included style sheets that do not print a true white background. Including any dark themes is useless to include with a plugin for printing, the light ones without true white background should be simple to fix. This is however something that users of the plugin should not have to bother with. Having many style sheets included that provide poor output gives a poor (first) UX that can be easily prevented. Be aware that most users will use the plugin without being aware of its internal workings.
> Your plugin is very promising but I have not found a style sheet yet that provides the same richness of the syntax coloring in the editor. As alternative for richer syntax coloring I still print my code in NotePad++ but that is not preferable and is an inefficient workflow.

VS Code extensions are written in Typescript, so they use JS libraries. `highlight.js` is about as good as it gets on several fronts. Doing a better job would require active support from the people responsible for VS Code and I can't even persuade them to support putting "Print" in the File menu where it belongs.

**Comment by PeterWone** [comment]
@ADBeasley @lnlp @phenry-Fusebill 

You may be interested in #86
