### ISSUE TITLE
Does not support remote coding

### ISSUE THREAD

**Issue by ADBeasley** [PeterWone/vsc-print#76]
Using VS Code on a Mac, if the source is located on a remote computer (e.g. SSH on a Raspberry Pi) you cannot print via the editor window.

**Actions seen:**
No browser shows when the print icon is clicked.

**Expected action:**
Browser on the _local_ machine should be opened

**Settings tried:**
Installing the extension in the remote does not help
Changing the alternate browser check box to off does not help

**Work around is:**

- Open the directory containing the code using finder (requires access to a share on the target machine)
- Seelct the code with left click - Open in VSCode
- Select print from this window

**Comment by PeterWone** [comment]
Apple won't let me run OS/X on a VM and I'm not going to buy a Mac to debug free software. This is, however, an opportunity for open source to live up to the legend - are you interested in taking this on?

**Comment by ADBeasley** [comment]
A VM can be done but its not easy and TBH the license is so long I'm sure they say no to every possible use case (esp if you do not have a legit Mac).

Happy to help - I'm off work with mental health issues (and computers do not always help) so it may take a while to do things and it may be at odd hours (UK time) when I come back to you.  My programming skills are way out of date and basic but I'll shout if I get stuck.  No Windows licence for my Mac but I have VM Fusion and Parallels (do not ask why I have both) that I can create Linux and Mac images on.  No Docker skills at all.

The SSH method works fine on the Pi and a stock Debian VM I have but on the Pi it needs to be a Stretch Raspberry Pi OS or above (i.e. Buster) and I never got it working on a Pi Zero (the install complained about 32bit but cannot remember the full error now) - works fine on my 3B or 3B+ box.

I set up SSH as follows:

1. Set up SSH on the target (built-in on the Pi and Debian image I used) - OpenSSH is fine
2. SSH is installed on the Mac - I assume you would use OpenSSH on Windows rather than the GUI PuTTY for this.
2. Added an entry to UFW rules for SSH on port 22
2. Check it works from your host machine with `ssh user@target.local` (well Windows equivalent)
3. I generated a SSH key using `ssh-keygen` on the Mac
4. Copied that over the the Pi using `ssh-copy-id user@target.local`
5. Added an entry to my .ssh/config file to provide user and limit to IPv4:
```
Host study
  HostName study.local
  AddressFamily inet
  User pi
```
I then added the Remote Development extension to the Mac in VS Code - note the MS notes talk about needing Docker but that's not needed on the target.  It's documented [by MS here](https://code.visualstudio.com/docs/remote/ssh) but I just Googled how to do it for a Raspberry Pi :-)

After a restart of VS Code you get an option bottom left of the edit window to connect to a remote system:

![Screenshot 2021-02-07 at 13 40 08](https://user-images.githubusercontent.com/39886283/107148220-09551780-694a-11eb-8040-bf8c3c02bcc4.png)

Clicking on this 'zigzag' gives you the option to connect a window to a host:

![Screenshot 2021-02-07 at 13 41 10](https://user-images.githubusercontent.com/39886283/107148265-3efa0080-694a-11eb-94bf-74210e94c2d3.png)

and then you can select the host you need:
![Screenshot 2021-02-07 at 13 41 34](https://user-images.githubusercontent.com/39886283/107148288-5638ee00-694a-11eb-85c4-cad1577abe1c.png)

Note the first set of entries are from my .ssh/config file but these entries are optional if you just type the host details in.  Not sure where this file is on a PC - [this Stack Exchange answer maybe valid](https://superuser.com/questions/1537763/location-of-openssh-configuration-file-on-windows)

First connection will spend a fair bit of time loading support tools onto the remote (and its **a lot** of tools / folders) and you need to add extensions remotely as well I'm finding (python needs the extension to handle syntax checking through pylint for example).

Once installed I just create code in the remote session using the VS Code directory browser and editor as if it was my local machine.

I have Netatalk running on the Pi to give me file access (I know Samba works as well) from the Mac and use that just to back up the work using Carbon Copy - hence trying to use a file share to print from.

**Comment by baincd** [comment]
I wonder if #96 might resolve this issue as well

**Comment by PeterWone** [comment]
Chris, I apologise for not having processed your recent contributions. Just at the moment I’m having trouble finding enough time for my own work. Please bear with me.

**Comment by baincd** [comment]
@PeterWone No need to apologize, I completely understand.  I appreciate all the time you've put in to maintaining this extension, and hope I've been able to help out a little bit.

**Comment by PeterWone** [comment]
Recently I've had to work with the VS Code Remote Docker extension and as a result I have acquired some understanding of a closely related problem. The long and the short of it is the extension resolves paths either locally or in the remote filesystem, depending on the extensionKind setting, and since the stylesheets are always in the local filesystem it fails when trying to find them in the remote filesystem.

As this was brought up by a user of VS Code Printing during a DockerCon session hosted by a Microsoft person I piped up and later worked with Microsoft trying to resolve this, leading to the above insight.

The only workaround I can see is removing support for user defined stylesheets and putting a few of the better choices into the webpack bundle so they can resolve independent of the filesystem.

**Comment by PeterWone** [comment]
You fixed botched initial config but setting extensionKind to ui just makes it exhibit the same behaviour as no setting at all. 

> In order to make working with Remote Development or Codespaces as transparent as possible to users, VS Code distinguishes two kinds of extensions:
>
> * UI Extensions: These extensions contribute to the VS Code user interface and are always run on the user's local machine. UI Extensions cannot directly access files in the remote workspace, or run scripts/tools installed in that workspace or on the machine. Example UI Extensions include: themes, snippets, language grammars, and keymaps.
> * Workspace Extensions: These extensions are run on the same machine as where the workspace is located. When in a local workspace, Workspace Extensions run on the local machine. When in a remote workspace or when using Codespaces, Workspace Extensions run on the remote machine / environment. Workspace Extensions can access files in the workspace to provide rich, multi-file language services, debugger support, or perform complex operations on multiple files in the workspace (either directly or by invoking scripts/tools). While Workspace Extensions do not focus on modifying the UI, they can contribute explorers, views, and other UI elements as well.
>
> When a user installs an extension, VS Code automatically installs it to the correct location based on its kind. If an extension can run as either kind, VS Code will attempt to choose the optimal one for the situation. UI Extensions are run in VS Code's local Extension Host, while Workspace Extensions are run in a Remote Extension Host that sits in a small VS Code Server. To ensure the latest VS Code client features are available, the server needs to match the VS Code client version exactly. Therefore, the server is automatically installed (or updated) by the Remote Development or GitHub Codespaces extensions when you open a folder in a container, on a remote SSH host, using Codespaces, or in the Windows Subsystem for Linux (WSL). (VS Code also automatically manages starting and stopping the server, so users aren't aware of its presence.)

What I'm saying above is that setting it to "workspace" seems to interfere with access to locally installed template files. If I put them in the bundle the problem will go away but that limits your option to whatever stylesheets I bundle.

This is not the worst idea ever. It would allow us to prevent stupid choices and make all the options good ones, and the picker UI could be a combobox.

**Comment by baincd** [comment]
I follow all that, what I'm not following is the reason for wanting to change the extension to be installed as a workspace extension.  

Thinking about it, maybe the markdown rendering doesn't work?  Admittedly I didn't test that.  If that's the issue, then it seems like it comes down to which is more valuable to support for remote workspaces - user-defined stylesheets or markdown rendering.

**Comment by PeterWone** [comment]
Doing so (combined with the remoting extensions) lets you work on the filesystem that's inside a docker container or WSL.

**Comment by PeterWone** [comment]
Got a few ducks to line up first but this is on the way. 

* Stylesheets are going to have to be bundled so that they remain accessible when the file system is redirected to a container.
* If stylesheets are bundled that means no more BYO stylesheets. Which means...
  * A couple of core stylesheets for syntax colouring
  * Direct settings for customisation on a hot preview with code and markdown samples 
  
I'm thinking of setting up a feedback page laying out the options and motivations and releasing an update with a notification pointing people at it.

**Comment by PeterWone** [comment]
Stylesheets are now bundled (code printing syntax-colour schemes) and Markdown customisation is now handled directly. This means no reliance on local file system access.

![image](https://user-images.githubusercontent.com/5498936/131256833-73640d6a-5e73-43b7-8a5c-8738ab6f5fce.png)

![image](https://user-images.githubusercontent.com/5498936/131256926-8a4b1f9e-1bf3-4073-89af-33a63cee64ad.png)

**Comment by PeterWone** [comment]
@ADBeasley Everything's bundled now. Let me know whether this resolves the issues with filesystem redirection in containers and remoting.

**Comment by PeterWone** [comment]
@ADBeasley Guess what's in the next release

![image](https://user-images.githubusercontent.com/5498936/133368371-16530169-0745-4b28-8449-ffac3fac5f9f.png)

**Comment by PeterWone** [comment]
@ADBeasley  If you don't think 0.9.12 meets the need let me know and we can re-open this.

**Comment by ADBeasley** [comment]
@PeterWone Sorry to say I'm currently mental not well enough to be coding let alone testing things :-(
