### ISSUE TITLE
What is the relation between VSCode themes and vsc-print themes?

### ISSUE THREAD

**Issue by lnlp** [PeterWone/vsc-print#77]
What is the relation between VSCode themes and your Visual Studio Code Printing (vsc-print) themes/stylesheets?

At first I had the impression that I could specify any of the themes defined in VSCode but when using the command 'Browse for stylesheets' folder `C:\Users\<username>\.vscode\extensions\pdconsec.vscode-print-0.8.3\node_modules\highlight.js\styles` opens with .css files that do not match themes defined in VSCode.

I see little documentation for the structure of the included .css files.
What are the included stylesheets based upon?
Is there any more information about this?
Where to find more styles other than the ones included?
Is there a way to previewthese styles, whithout having to set them as print style and (preview) print a document first?

Is it (somehow) possible to use one of the Themes defined in VSCode instead?

**Comment by PeterWone** [comment]
Well... they are all CSS, and VS Code is open source. So there's no reason you couldn't fish their CSS out and use it.

Style preview... that's not a bad idea. Make it an issue. Hopefully someone will take it on (I'm rather busy at work just now).

**Comment by PeterWone** [comment]
Default theme after installation is now atelier dune. This will take effect in the next release.
