### ISSUE TITLE
Glob not matching anything for printing folder

### ISSUE THREAD

**Issue by PeterWone** [PeterWone/vsc-print#82]
@Alainx277 

![image](https://user-images.githubusercontent.com/5498936/111103833-0d083980-859b-11eb-8894-453f37327ae5.png)

If you look at the screen snap you'll see I tried to print a folder of dotnet webcontrollers. The outcome was an empty document. A trace revealed the glob failed to match at the point shown in the snap. This folder contains several CS files. I can't see why the glob didn't match them. 

Would you mind updating your fork to have a look at that please? I have no time for this at the moment but would really like to put out a release including this feature. 

When I pass `${filePath}/*.*` without the exclusions instead of fullPattern it finds them. I tested on Windows 10.

**Comment by PeterWone** [comment]
This may be relevant https://github.com/isaacs/node-glob/issues/180

**Comment by Alainx277** [comment]
Wow, that's embarrassing. Turns out testing at 1 am isn't a good idea.
I'll get this fixed up.
