### ISSUE TITLE
Support printing rendered markdown in unsaved files

### ISSUE THREAD

**Issue by baincd** [PeterWone/vsc-print#98]
Markdown files only printed rendered as HTML if the file has been saved as a .md file.  Ideally, the file language should be used.

This might be tricky with the current implementation - where the markdown is rendered, there is no reference to the vscode editor.

There would also not be a way to print images in the rendered markdown, since there is no way to determine the path (could default to the project path, but if there is no project or multiple folders this doesn't work).  I think the limitation that unsaved markdown files would not print images is OK.

I don't know that this is worth supporting unless there is clear interest in this feature.

**Comment by PeterWone** [comment]
![image](https://user-images.githubusercontent.com/5498936/114947766-0c600d00-9e91-11eb-8915-9c63b5b7585f.png)

`Ctrl+K` `M` then type the language you want

![image](https://user-images.githubusercontent.com/5498936/114947640-d4f16080-9e90-11eb-8fc0-bf6ac68c018b.png)
Voila!

![image](https://user-images.githubusercontent.com/5498936/114947706-f3eff280-9e90-11eb-99a8-22f155be4841.png)

**Comment by baincd** [comment]
@PeterWone FYI, the scenario this issue is actually referring to is:

Render Markdown enabled:
![image](https://user-images.githubusercontent.com/5075659/114955741-57dfd000-9e2b-11eb-99de-fd6da9e764ca.png)

New file (unsaved) with language changed to Markdown:
![image](https://user-images.githubusercontent.com/5075659/114955862-98d7e480-9e2b-11eb-80e7-cc213061bd17.png)

Click print, and the code is printed rather than rendered markdown:
![image](https://user-images.githubusercontent.com/5075659/114955971-d472ae80-9e2b-11eb-84b0-29d106579a3d.png)

This also happens on a saved file that does not end with .md:
![image](https://user-images.githubusercontent.com/5075659/114956150-4c40d900-9e2c-11eb-8a9a-afe24926bcf6.png)

I think the expected behavior is to print the rendered markdown in both these scenarios.

The reason for the current behavior is [this line](https://github.com/PeterWone/vsc-print/blob/91b1a5c80f00cebbc542175a46dd4c78124af6e9/src/extension.ts#L259) - ideally I think it should be checking the editor language rather than the filename extension.  However, that could be tricky as the editor is not directly available within that function.

Re: images - absolute paths would work on unsaved files (and #97 even fixes the issue with them not working on Linux as well).  But I wouldn't expect absolute paths to be common in markdown files (but I'm sure there is a use case for it somewhere :wink: ).  My original point though was to note that there was a potential use case where images wouldn't be printed in the rendered markdown - unsaved markdown-language file with image links using relative file paths - but that I think that's OK.

**Comment by PeterWone** [comment]
You're right. It's a marginal case but we'll fix it anyway because we can. I hope to process your outstanding PRs this weekend.

**Comment by baincd** [comment]
I was already thinking about how capturing the state at the beginning and passing it around could be used to simplify some of the logic (and might even reduce the potential for bugs in the future).  So adding that could have more benefits than just to fix this issue.  Of course I'm sure I don't need to tell you about the potential risk of improving code that already works :wink: .

That other project sounds really cool.  Thank you for the offer, however I'm going to pass.

**Comment by PeterWone** [comment]
No prob. I thought I'd raise it because you seem interested in printing rendered markdown.

**Comment by PeterWone** [comment]
Done.  Will be in 0.9.15
